import * as React from "react";
<% if (semantic) { %>
import { Header, Icon } from 'semantic-ui-react';
<% } %>

const App: React.FC = () => (
    <% if (semantic) { %>
    <>
        <br />
        <Header as='h1'>
            <%= appName %>
        </Header>
        <br />  
        <Header as='h2'>
            This is project generated by parcel-web-app generator!
            <Icon name="hand peace outline" />
        </Header>
    </>
    <% } else { %>
    <>
        <h1><%= appName %></h1>
        <br />
        <p>This is project generated by parcel-web-app generator!</p>
    </>
    <% } %>
);

export default App;
